### ISSUE TITLE
setHeaderRoute error and memory leak

### ISSUE THREAD

**Issue by dtelaroli** [argoproj/argo-rollouts#3276]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/argoproj/argo-rollouts/assets/536500/535af8fc-d484-4dab-af7e-2ba45ffc2c4f)

**Version**

v1.5.0

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME

time="2023-12-27T15:38:47Z" level=info msg="Started syncing rollout" generation=359 namespace=psm-test resourceVersion=3287885544 rollout=clismo
time="2023-12-27T15:38:48Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=psm-test rollout=clismo
time="2023-12-27T15:38:48Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=psm-test rollout=clismo
time="2023-12-27T15:38:50Z" level=warning msg="Request entity too large: limit is 3145728" event_reason=TrafficRoutingError namespace=psm-test rollout=clismo
time="2023-12-27T15:38:50Z" level=error msg="roCtx.reconcile err Request entity too large: limit is 3145728" generation=359 namespace=psm-test resourceVersion=3287885544 rollout=clismo
time="2023-12-27T15:38:50Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"psm-test\", Name:\"clismo\", UID:\"15051ab3-a968-4673-b1af-55ac0a8c525d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"3287885544\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' Request entity too large: limit is 3145728"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I think this is possibly fixed in 1.6, could you try 1.6.4?

**Comment by dtelaroli** [comment]
Hi @zachaller 
I have another issue that is a block for me upgrade the argo-rollouts.
https://github.com/argoproj/argo-rollouts/issues/3223

**Comment by dtelaroli** [comment]
Anyway, the PR https://github.com/argoproj/argo-rollouts/pull/2887 fixes the problem 1, it doesn't solve the problem 2.

**Comment by dtelaroli** [comment]
@andyliuliming i've discovered that the issue happens when you have a big manifest synced by the application.
There is a limit of size and when the size is over the limit the argo-rollouts dispatch error each sync cicle and this generates the memory leak. `Request entity too large: limit is 3145728`
Fixing the big manifest, the issue disappear.

Another issue that I had is because the rollouts adds a empty step during the setHeaderRoute: `- {}`
This brakes the rollouts also, generating memory leak.
