### ISSUE TITLE
Use of native SidecarContainers (init container with `restartPolicy: Always`) results in pod status getting stuck on `Init`

### ISSUE THREAD

**Issue by martynd** [argoproj/argo-rollouts#3366]
K8s 1.29 enables the `SidecarContainers` feature gate by default (more info on the native sidecars here https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)
These are defined as `initContainers` with the `restartPolicy` set to `Always`

This change in logic results in pods being perpetually (visually) stuck in the Init phase

This appears to have affected various software which interacts with k8s, eg the following issue on `k9s`
https://github.com/derailed/k9s/issues/2520

**Screenshots**
![Screenshot 2024-02-13 at 11 07 29 AM](https://github.com/argoproj/argo-rollouts/assets/669891/c2ebe23b-da86-4df5-a945-7e76e87d5106)

```
Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by phyzical** [comment]
We will also need to add logic to allow the spec to support redinessProbe and startupProbe for  ` initContainers` with the `restartPolicy` set to `Always`

```
 spec.template.spec.initContainers[1].readinessProbe: Forbidden: may not be set for init containers
 ```

**Comment by phyzical** [comment]
I gave  "release-1.7" tag a go, didn't help sadl.

 turns  out i missed part of the error from before its actually ` is invalid: spec.template.spec.initContainers[1].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always`
 
 So i wondered if the restart policy for normal containers propagated, and it turns out it doesnt for that either.
 
 that makes me think this is by design and couuuld explain the side effects your experiencing ? @martynd 
 
 Ill have another sniff at the source to see if theres any comments as to why it does this

**Comment by Hronom** [comment]
Pretty actual, it's appear to be a blocker to enable native sidecars for istio as sidecars now can't work properly with Argo Rollouts.

This one is critical to release

**Comment by sherifabdlnaby** [comment]
This is very important! It's blocking us from using Argo Rollouts

**Comment by nsaini-figma** [comment]
Is this fixed in 1.8.0? I see the [commit](https://github.com/argoproj/argo-rollouts/commit/6c873a95ec34e141243cc5e3846c69c9ce1c42d3) that has the fix in the 1.8.0 code, but it looks like a subsequent [commit](https://github.com/argoproj/argo-rollouts/commit/bfef7f0d2bb71b085398c35ec95c1b2aacd07187) deletes this code? I am still seeing this behavior in 1.8.0.

**Comment by stav-caspi** [comment]
This issue still exists.
I tried both v1.8release and 1.8.2, both fail with the same behavior, the side car container gets created, but as an init container, we can see the containers start up correctly but never becomes ready, always stays in init phase.
@meeech any suggetion?
